services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    db:
        container_name: mysql_task
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "33066:3306"
        volumes:
            - database:/var/lib/mysql

volumes:
    database: ~
